mise.toml, packages/eql-mapper/src/importer.rs, packages/eql-mapper/src/inference/infer_type_impls/function.rs, packages/eql-mapper/src/inference/registry.rs, packages/eql-mapper/src/lib.rs
SQL statements containing literals or param placeholders currently trigger type check error. 
```
-- The arg `'x'` causes mapping to fail.
-- This causes `encrypted_text` to fail to decrypt in the results.
select concat(plaintext, 'x'), encrypted_text from encrypted;
```
This change unifies function types with `Type::any_native()`. 
EQL values will be rejected in function calls, which is the correct behaviour in most situations as EQL columns need to be decrypted. 
eg, `concat(encrypted_column, 'str')` will attempt to concat the encrypted json data. 
Future work will add support for the EQL functions.
=> Functions with literals and params should type resolve

.github/workflows/release.yml
Previous GitHub runner group doesn't run on public repos.
New more restrictive runner group has been created, and label should match.
=> build(ci): make release workflow run now repo is public

Cargo.lock, packages/cipherstash-proxy-integration/Cargo.toml, packages/cipherstash-proxy-integration/src/simple_protocol/error_handling.rs, packages/cipherstash-proxy-integration/src/simple_protocol/mod.rs, packages/cipherstash-proxy-integration/src/simple_protocol/multiple_statements.rs, packages/cipherstash-proxy/src/error.rs, packages/cipherstash-proxy/src/postgresql/backend.rs, packages/cipherstash-proxy/src/postgresql/context/mod.rs, packages/cipherstash-proxy/src/postgresql/frontend.rs
Parse simple query messages into Vec of Statement AST/s and encrypt each statement if required.
Adds new EncryptedText variant of Portal to distinguish Simple Protocol in the backend
=> fix(mapper): handle multiple statements in simple query messages

packages/cipherstash-proxy-integration/src/map_ore_index_where.rs
Adds `null` record to ORE operator tests. Test behaviour is unchanged, null records should now be excluded from comparison, following existing PostgreSQL behaviour.
Fix is in EQL ore here https://github.com/cipherstash/encrypt-query-language/pull/94
=> test(eql): Add null record to ORE operator tests

Cargo.lock
Last merge commit (61fad6199b904e746bb0ee3c08c54ee6be79a353) on `main` has a [failing check](https://github.com/cipherstash/proxy/actions/runs/13780037617/job/38536506825).
`Cargo.lock` is out of sync with `Cargo.toml`. 
This fixes that.
=> fix: update `Cargo.lock` based on current `Cargo.toml`

mise.toml
Background: 
- Last merge commit (61fad6199b904e746bb0ee3c08c54ee6be79a353) on `main` has a failing check
- The `release.yml` workflow is trying to build a binary, but [it is failing](https://github.com/cipherstash/proxy/actions/runs/13780037617/job/38536506825) because `Cargo.lock` will change:
```
$ cargo build --locked --release --package cipherstash-proxy
Updating crates.io index
error: the lock file /home/runner/work/proxy/proxy/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```
This brings the `Cargo.lock` check into the normal PR review, so issues can be identified earlier.
=> test: check that `Cargo.lock` is up to date

Cargo.lock, packages/cipherstash-proxy/Cargo.toml, packages/cipherstash-proxy/src/config/tandem.rs, packages/cipherstash-proxy/src/tls/mod.rs
Latest state of the art in Rustls is `rustls-platform-verifier` to verify the validity of TLS certificates
https://github.com/rustls/rustls-platform-verifier
=> fix(deps): Add rustls-platform-verifier for certs

mise.toml
Has the `mise run build:docker` task print its Docker build output (with `--progress=plain`), so it's possible to see said output after the run has finished.
=> build(mise): DEBUG flag now has the `build:docker` task retain its build output.

Cargo.lock, README.md, mise.toml, packages/cipherstash-proxy-integration/Cargo.toml, packages/cipherstash-proxy-integration/src/lib.rs, packages/cipherstash-proxy-integration/src/migrate/mod.rs, packages/cipherstash-proxy/src/cli/migrate/mod.rs, packages/cipherstash-proxy/src/cli/mod.rs, packages/cipherstash-proxy/src/config/tandem.rs, packages/cipherstash-proxy/src/eql/mod.rs, packages/cipherstash-proxy/src/lib.rs, packages/cipherstash-proxy/src/log/mod.rs, packages/cipherstash-proxy/src/main.rs, tests/tasks/test/integration/migrate.sh
Migrator command assumes a running proxy, and uses existing config to make the connection. 
Streamlines the migrate options, as only table and source/destination columns are required. 
- command line exec via docker 
- rust integration test via direct call
Example usage
```bash
cipherstash-proxy encrypt --table encrypted --columns plaintext=encrypted_text
```
=> feat(migrate): Import migrator code and add as proxy subcommand

docker-entrypoint.sh, proxy.Dockerfile
AWS RDS instances use a separate SSL CA and set of certificates to the Amazon root CA:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
To connect via SSL to RDS, without changing the CA for the RDS instance, we need to pull in the AWS-provided certificate bundle.
To accomplish this, we have an entrypoint wrapper script (`cipherstash-proxy.sh`) that, at container start, optionally installs the bundle and then goes on to run the `cipherstash-proxy` binary. Set the `CS_DATABASE__INSTALL_AWS_RDS_CERT_BUNDLE` env var (eg. to `"true"`) for the container to load that bundle.
(The certificate bundle itself is fetched *at build time* for later run-time use; as long as the proxy image isn't extremely old, it should be fine.)
This PR builds on #159.
=> feat: Have the AWS RDS certificate bundle be optionally loaded into the system cert store.

mise.toml, tests/sql/schema-uninstall.sql
Ensure `unconfigured` table is torn down at the end of test runs and also swap order of schema & EQL teardown to prevent teardown failures when EQL types are still referenced.
=> fix(tests): missing table in teardown & order of schema & EQL teardown

.github/workflows/release.yml
The final push to Docker Hub should not happen on PRs.
But it should happen on merges to `main`.
=> fix(release): make releases on push to `main` work again

README.md, docker-compose.yml, docker-entrypoint.sh, mise.toml, proxy.Dockerfile, tests/docker-compose.yml
Running the Proxy container and setting `CS_DATABASE__INSTALL_EQL=true` will install EQL into the target database. 
This PR also:
- [Documents](https://github.com/cipherstash/proxy/pull/157/commits/42ff8e44e13ecceeac11d78248287ccdc18b5254) how to install EQL using the environment variable
- [Refactors](https://github.com/cipherstash/proxy/pull/157/commits/8bd8be7dea0c20bd3a0fd8471bf7ff8c180a97e0) building of a `cipherstash-proxy` binary into a reusable task
- [Cleans up](https://github.com/cipherstash/proxy/pull/157/commits/25adddc79ae851f3314e0b06ee63bdc9640fdbc5) whitespace in `docker-compose.yml`
=> feat: optionally trigger EQL install on container start

docs/errors.md, packages/cipherstash-proxy-integration/src/extended_protocol_error_messages.rs, packages/cipherstash-proxy/src/error.rs, packages/cipherstash-proxy/src/postgresql/frontend.rs
This changes error mapping target of EqlMapper::InternalError from `MappingError::StatementCouldNotBeMapped` to a newly created error type `MappingError::Internal`. Also adds a new section in the docs.
I think this is better as "statement could not be mapped" can be user-side issue (like 4XX errors in HTTP), but internal error is server-side (like 5XX in HTTP).
It still does the same logging and counting as `StatementCouldNotBeMapped` but the raised (mapped) error and its messages are distinct from `StatementCouldNotBeMapped`.
=> feat: improve error message for internal errors

packages/cipherstash-proxy/src/config/database.rs, packages/cipherstash-proxy/src/connect/mod.rs, packages/cipherstash-proxy/src/error.rs, packages/cipherstash-proxy/src/main.rs, packages/cipherstash-proxy/src/postgresql/backend.rs, packages/cipherstash-proxy/src/postgresql/frontend.rs, packages/cipherstash-proxy/src/postgresql/handler.rs, packages/cipherstash-proxy/src/postgresql/messages/error_response.rs, packages/cipherstash-proxy/src/postgresql/protocol.rs, packages/cipherstash-proxy/src/postgresql/startup.rs
Replicate postgres behaviour by making connection timeout optional. 
Timeout is still configurable, but default is no timeout.
=> fix: make connection timeout optional

DEVELOPMENT.md
Explicitly state in `DEVELOPMENT.md` that the Docker daemon should be launched.
=> docs: explicitly state that docker daemon should be started

mise.local.example.toml, mise.toml
This is relevant to tests and building the Docker image; that EQL version will be baked-in once the Docker image has been released and is not customer-modifiable.
=> feat(proxy): lock EQL to specific version via `CS_EQL_VERSION`

mise.local.example.toml, mise.toml, packages/cipherstash-proxy/src/encrypt/mod.rs, packages/cipherstash-proxy/src/main.rs
This queries the database with `select cs_eql_version();` (rather than the version at build time) for accuracy.
=> feat(proxy): output installed EQL version on startup

proxy.Dockerfile
Docker Scout says this will eliminate 11 known vulnerabilities in package dependencies.
The base image for 24.04 has not been updated for several months, which is unusual for an LTS release.
=> chore(docker): upgrade Ubuntu base image to 24.10

.gitignore, packages/cipherstash-proxy/build.rs, packages/cipherstash-proxy/src/main.rs
1. mise.toml downloads the EQL version specified in `CS_EQL_VERSION`
2. `cipherstash-proxy` now has a `build.rs` file that reads `CS_EQL_VERSION` at compile time.
3. The env var is consumed (at compile time) in `cipherstash-proxy`'s `main.rs` and stored in a constant
4. When `Encrypt` is initialised the version from the database is compared with the version from compile time and a `warn!(..)` is issued when they differ.
=> feat(proxy): emit warning when proxy build-time and runtime versions of EQL differ

docs/errors.md, packages/cipherstash-proxy/src/error.rs, packages/cipherstash-proxy/src/postgresql/frontend.rs, packages/eql-mapper/src/eql_mapper.rs
This updates the `errors.md` and adds details for Statement could not be type checked or StatementCouldNotBeMapped.
=> Add details of StatementCouldNotBeMapped in errors.md

README.md
Explain how to set up the database schema to add encrypted columns. 
Also: small fixes to syntax and improve docs maintainability.
=> docs: explain how to add encrypted columns to schema

Cargo.toml, packages/cipherstash-proxy/Cargo.toml, packages/eql-mapper/Cargo.toml
Not for merge yet, but what it says on the tin.
=> chore: bump Rust package version numbers for release

packages/cipherstash-proxy/src/postgresql/messages/authentication/auth.rs
This fixes build error due to rustc 1.86.0 upgrade
=> chore: update code so it builds on 1.86.0

mise.toml
This makes proxy not start if the build fails.
Without this:
With this:
=> chore: Make proxy not start on build failure

.github/ISSUE_TEMPLATE/docs-feedback.yml
Added a template to collect feedback on docs.
=> Chore: add template for docs issue form

README.md, docs/reference.md
=> Docs: Add link to request x86_64 Docker image

packages/cipherstash-proxy-integration/src/common.rs, packages/cipherstash-proxy-integration/src/passthrough.rs
Adds additional passthrough tests to cover some of the more obscure SQL syntax encountered in the wild. 
Covers
- insert from select
- insert with value from select
- insert with returning
- delete with select subquery
=> Expand passthrough test cases

packages/eql-mapper/src/inference/infer_type_impls/expr.rs, packages/eql-mapper/src/lib.rs
A "named" array (in `sqlparser` parlance) is an array value with syntax like `ARRAY[1, 2, 3]` as opposed to `[1, 2, 3]`.
That's it.
I must have thought it meant something exotic at the time I wrote the original code.
=> fix(mapper): support named arrays

mise.toml, packages/cipherstash-proxy/src/config/log.rs, packages/cipherstash-proxy/src/error.rs, packages/cipherstash-proxy/src/log/mod.rs, packages/cipherstash-proxy/src/log/subscriber.rs, packages/cipherstash-proxy/src/postgresql/backend.rs, packages/cipherstash-proxy/src/postgresql/context/mod.rs, packages/cipherstash-proxy/src/postgresql/frontend.rs, packages/cipherstash-proxy/src/postgresql/messages/data_row.rs
EQL 2.0 changes the internal type representation of encrypted records to use a PostgreSQL composite type.
Returned values are wrapped as a tuple `("{ ... }")`
When decrypting returned records, the json needs to be extracted.
=> Eql v2 decryption

packages/cipherstash-proxy-integration/src/extended_protocol_error_messages.rs, packages/cipherstash-proxy/src/postgresql/backend.rs, packages/cipherstash-proxy/src/postgresql/messages/data_row.rs
When using binary encoding with a null value in a `RowType` the `DataColumn` contains a header that contains the field length information. 
This adds a check for a `NULL` len in the binary `DataColumn` header.
If a `NULL` column is found, the column bytes are rewritten to be `NULL` (removing the header)
This works because the returned type is the `cast` type of the configured column, which is not a `RowType` and the vanilla `NULL` encoding is expected.
=> Handle data row with binary encoding and null

packages/cipherstash-proxy-integration/src/map_concat.rs, packages/cipherstash-proxy/src/encrypt/mod.rs, packages/cipherstash-proxy/src/eql/mod.rs, packages/cipherstash-proxy/src/postgresql/backend.rs, packages/cipherstash-proxy/src/postgresql/messages/data_row.rs, packages/eql-mapper/src/lib.rs, packages/eql-mapper/src/transformation_rules/cast_literals_as_encrypted.rs, packages/eql-mapper/src/transformation_rules/cast_params_as_encrypted.rs, packages/eql-mapper/src/transformation_rules/helpers.rs, packages/eql-mapper/src/transformation_rules/mod.rs, packages/eql-mapper/src/type_checked_statement.rs
Fix for SQL error when using `ore` or `unique` index terms:
```
operator is not unique: eql_v1_encrypted > record
```
Encrypted parameters and literals are currently being wrapped into a `ROW` which create a value of type `record`.
This explicitly casts literals and params as `::jsonb::eql_v1_encrypted`
=> Cast literals and params to `eql_v1_encrypted`

docs/errors.md, docs/how-to.md, packages/cipherstash-proxy/src/error.rs, packages/cipherstash-proxy/src/postgresql/backend.rs
Check the identifier in the returned ciphertext matches the identifier in the column configuration before decryption. 
Returns an error if a mismatch is detected. 
Helps protect against confused deputy attacks.
=> feat: check column configuration against encrypted column before decrypt

.github/workflows/release.yml, mise.toml
=> feat(docker): add builds for multi-platform docker images

packages/cipherstash-proxy/src/config/tandem.rs
Variables like `CS_CLIENT_KEY` have aliases, such as `CS_ENCRYPT__CLIENT_ID`. With these variables set, testing for absence of client key configuration will still find the client key configuartion. This commit makes those tests unset any `CS_*` variable defined outside of the tests.
=> fix: make tests ignore CS_ vars when testing for missing config

mise.toml, packages/cipherstash-proxy-integration/src/decrypt/insert_returning.rs, packages/cipherstash-proxy-integration/src/decrypt/mod.rs, packages/cipherstash-proxy-integration/src/lib.rs, packages/cipherstash-proxy-integration/src/map_nulls.rs, packages/cipherstash-proxy/src/postgresql/frontend.rs, packages/cipherstash-proxy/src/postgresql/messages/bind.rs, tests/sql/schema.sql
Fixes issue with encoding `NULL` parameter values in Bind messages.
`NULL` params are of length 0, but the length is encoded in a Bind message as `-1`.
=> Fix for "Error: insufficient data left in message" with null values

packages/cipherstash-proxy-integration/src/common.rs, packages/cipherstash-proxy-integration/src/insert/insert_with_literal.rs, packages/cipherstash-proxy-integration/src/insert/insert_with_null_literal.rs
Adds simple query to the insert literal tests
=> test: add simple query to insert literal tests

.github/workflows/release.yml
The release workflow running on the beefier GitHub Actions runners are taking [a really long time](https://github.com/cipherstash/proxy/actions/runs/15381882760/job/43273890921) (cancelled at 33 minutes). 
Switch to the BuildJet runners, which we know run much faster for x86_64 builds. 
=> build: use faster x86_64 runners from BuildJet

.github/workflows/release.yml
Per #234:
- We build Docker images for all PRs
- We publish Docker images tagged with the PR number [to Docker Hub](https://hub.docker.com/r/cipherstash/proxy/tags?name=pr-). 
This can be helpful for people testing out changes in PRs, but with these downsides:
- There are a lot of different image tags on Docker Hub, which can confuse users
- These builds end up costing a fair bit in build minutes
This PR changes the behaviour of GitHub Actions:
- We will not build and publish Docker images on PR branches
- We can still manually trigger the release workflow when we need to
=> chore: remove release on branch

packages/cipherstash-proxy-integration/src/select/unmappable.rs, packages/cipherstash-proxy/src/postgresql/frontend.rs, packages/cipherstash-proxy/src/postgresql/handler.rs, packages/cipherstash-proxy/src/postgresql/messages/error_response.rs
Extract a shared `error_handler` for query and parse handlers. 
Makes all mapping errors return a client error, wrapped as a PostgreSQL system error.
=> Refactor error handling and expand tests

mise.toml
It looks like golang and python weren't present in mise.toml. Enabling all.
=> chore: enable language-specific tests in test:integration

Cargo.lock, packages/cipherstash-proxy-integration/Cargo.toml, packages/cipherstash-proxy-integration/src/common.rs, packages/cipherstash-proxy-integration/src/decrypt/insert_returning.rs, packages/cipherstash-proxy-integration/src/insert/insert_domain_type.rs, packages/cipherstash-proxy-integration/src/insert/mod.rs, packages/cipherstash-proxy-integration/src/map_unique_index.rs, packages/cipherstash-proxy-integration/src/select/select_domain_type.rs, packages/cipherstash-proxy/src/postgresql/backend.rs, packages/cipherstash-proxy/src/postgresql/messages/param_description.rs, packages/cipherstash-proxy/src/postgresql/messages/row_description.rs, tests/integration/golang/README.md, tests/integration/golang/pgx_test.go, tests/sql/schema.sql
Remove the mapping from PostgreSQL OID to a `postgres_types::Type`, with unknown types being `unknown`.
When the Param and Row Description messages where rewritten for encryptable statements, the conversion left the OID as unknown rather than the original value. 
OIDs are now kept as the original `i32` value.
=> Handle PostgreSQL OIDs for custom and domain types

Cargo.lock, Cargo.toml, packages/eql-mapper/src/eql_mapper.rs, packages/eql-mapper/src/importer.rs, packages/eql-mapper/src/inference/infer_type_impls/expr.rs, packages/eql-mapper/src/inference/infer_type_impls/function.rs, packages/eql-mapper/src/inference/infer_type_impls/function_arg_expr.rs, packages/eql-mapper/src/inference/infer_type_impls/insert_statement.rs, packages/eql-mapper/src/inference/infer_type_impls/select_item.rs, packages/eql-mapper/src/inference/infer_type_impls/select_items.rs, packages/eql-mapper/src/inference/infer_type_impls/set_expr.rs, packages/eql-mapper/src/inference/infer_type_impls/statement.rs, packages/eql-mapper/src/inference/infer_type_impls/value.rs, packages/eql-mapper/src/inference/mod.rs, packages/eql-mapper/src/inference/sql_functions.rs, packages/eql-mapper/src/lib.rs, packages/eql-mapper/src/model/schema.rs, packages/eql-mapper/src/model/schema_delta.rs, packages/eql-mapper/src/model/table_resolver.rs, packages/eql-mapper/src/scope_tracker.rs, packages/eql-mapper/src/test_helpers.rs, packages/eql-mapper/src/transformation_rules/cast_literals_as_encrypted.rs, packages/eql-mapper/src/transformation_rules/cast_params_as_encrypted.rs, packages/eql-mapper/src/transformation_rules/fail_on_placeholder_change.rs, packages/eql-mapper/src/transformation_rules/helpers.rs, packages/eql-mapper/src/transformation_rules/preserve_effective_aliases.rs, packages/eql-mapper/src/transformation_rules/rewrite_standard_sql_fns_on_eql_types.rs, packages/eql-mapper/src/type_checked_statement.rs
This was a *mission*.
The main culprits were `ObjectName(Vec<Ident>)` changing to `ObjectName(Vec<ObjectNamePart>)` and `Expr::Value(Value)` changing to `Expr::Value(ValueWithSpan)`.
=> chore: fix all breakages due to type changes in sqlparser

.github/workflows/release.yml
Previously the [release workflow](https://github.com/cipherstash/proxy/actions/workflows/release.yml) would only run on push to `main` (triggering a push to the `main` tag on Docker Hub), or when it was manually invoked. 
Because we're using GitHub Releases to [cut new releases of Proxy](https://github.com/cipherstash/proxy/releases), we can eliminate the extra manual workflow invocation step. 
=> build: trigger release workflow on release event

mise.toml
Adds an additional version string to cipherstash-client's user agent header, to identify the version of CipherStash Proxy in use.
HTTP requests now look like this:
```
POST /load-dataset HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJS...
accept: */*
user-agent: cipherstash-client/0.22.2 (macos aarch64 cipherstash-proxy/v2.0.7)
host: ap-southeast-2.aws.viturhosted.net
content-length: 104
{"client_id":"8b6b222e-bbf5-4fda-ab50-67118d343a31","dataset_id":"a850f55e-b95f-4c1c-ba3e-a8a85349d999"}
```
=> build: send version string on requests to ZeroKMS/CTS

proxy.Dockerfile
According to Docker Scout:
- Image is smaller by 1.5 MB
- Image contains 10 fewer packages
- Tag was pushed more recently
- Image introduces no new vulnerability but removes 10
- Major OS version update
=> chore: upgrade container base image to Ubuntu 25.10

Cargo.lock, Cargo.toml, packages/cipherstash-proxy-integration/src/select/mod.rs, packages/cipherstash-proxy-integration/src/select/regression.rs
Update sqltk 0.10.0 and adds a regression test for IN clause subquery ORDER BY
=> Update sqltk 0.10.0

docs/getting-started/schema-example.sql, docs/how-to.md, mise.toml, tests/benchmark/sql/benchmark-schema.sql, tests/sql/schema.sql
Update to use `eql-2.1.0`
Makes the unused zero-downtime workflow optional and **disabled** by default.
Adding new search configuration no longer requires calling the `encrypt` and `activate` functions to move from `pending` to `active` config states.
```
-- No longer required
SELECT eql_v2.encrypt();
SELECT eql_v2.activate();
```
=> feat: update eql-2.1.0

mise.toml, packages/cipherstash-proxy-integration/src/select/jsonb_get_field.rs, packages/cipherstash-proxy-integration/src/select/mod.rs, packages/cipherstash-proxy/src/postgresql/context/column.rs, packages/cipherstash-proxy/src/postgresql/data/from_sql.rs, packages/cipherstash-proxy/src/postgresql/messages/bind.rs, packages/cipherstash-proxy/src/postgresql/messages/data_row.rs
Adds tests for JSONB field access operators (`->`)
Converts field names into a JSONPath selector for compatibility with `cipherstash-client`.
=> Tests for JSONB field access operator (`->`)

packages/eql-mapper/src/lib.rs, packages/eql-mapper/src/scope_tracker.rs
Resolutions of CTE tables would only succeed from the main statement of a `WITH` but not sub-statements of that statement.
The fix was to not create parentless scopes on entry to Statement nodes - instead create a new scope pointing to the parent scope.
=> fix(eql-mapper): resolution of CTE tables

.github/workflows/lint-test-chart.yml, .github/workflows/release-chart.yml
Hot fix for passing secrets on release 
=> fix(helm): PR_BYPASS specificlly pass secrets to lint job on release

packages/cipherstash-proxy/src/config/tandem.rs, packages/cipherstash-proxy/src/error.rs
crn parse error were being ignored - the variable was not set, leading to a "missing config" error message.
This change explictly handles parse errors caused by invalid `workspace_crn` and outputs an appropriate message
=> fix: error on invalid workspace_crn

mise.toml, packages/showcase/src/common.rs, packages/showcase/src/schema.rs
Adds the EQL Showcase tests (#285) to the set of existing integration test runs in CI.
=> ci(showcase): Adds Showcase to CI runs

.github/workflows/release-aws-marketplace.yml, .github/workflows/release.yml, packages/cipherstash-proxy-integration/src/map_ore_index_where.rs, packages/cipherstash-proxy/src/config/database.rs, packages/cipherstash-proxy/src/config/server.rs, packages/eql-mapper/src/inference/unifier/types.rs, packages/eql-mapper/src/type_checked_statement.rs
Add calls to deployment API on container release.
Call in `test.yml` is to verify that the call works, will removed before merge.
=> Send deployment notification to multitudes 

tests/python/tests/test_jsonb_array_elements.py, tests/python/tests/test_jsonb_array_length.py, tests/python/tests/test_jsonb_ops.py, tests/python/tests/test_jsonb_path_exists.py, tests/python/tests/test_jsonb_path_query.py, tests/python/tests/test_jsonb_path_query_first.py, tests/python/tests/test_jsonb_select_where_cmp.py, tests/python/tests/test_jsonb_select_where_eq.py
This PR adds integration test coverage for JSONB functions and operators, roughly analogous the JSONB tests in the `cipherstash-proxy-integration` suite.
A note to reviewer(s): these tests appear a little disjointed in style, ie.
- The `test_ops_…` and `test_select_where_…` tests are closer to the existing Python tests in style, but they started getting too copy-paste-y and overwrought for my liking the more I expanded the test coverage.
- For the rest of the new tests, I switched to match the `cipherstash-proxy-integration` tests instead (1-for-1, both per file and per individual test). I haven't yet been able to go back and change the earlier tests to match the latter, pardon.
By submitting this pull request, I confirm that CipherStash can use, modify, copy, and redistribute this …
=> Adds JSONB tests to the Python integration suite

.github/workflows/test.yml, Cargo.lock, Cargo.toml, docs/errors.md, packages/cipherstash-proxy-integration/src/common.rs, packages/cipherstash-proxy-integration/src/lib.rs, packages/cipherstash-proxy-integration/src/map_ore_index_where.rs, packages/cipherstash-proxy-integration/src/set_keyset_id.rs, packages/cipherstash-proxy/src/config/database.rs, packages/cipherstash-proxy/src/encrypt/mod.rs, packages/cipherstash-proxy/src/error.rs, packages/cipherstash-proxy/src/postgresql/backend.rs, packages/cipherstash-proxy/src/postgresql/context/mod.rs, packages/cipherstash-proxy/src/postgresql/error_handler.rs, packages/cipherstash-proxy/src/postgresql/frontend.rs, packages/cipherstash-proxy/src/postgresql/mod.rs, tests/docker-compose.yml
The Proxy should expose a `SET` command that enables run-time configuration of a `keyset_id`: 
```
SET CIPHERSTASH.KEYSET_ID = 'EXAMPLE-UUID-4b38-9571-e0cf47802677'
```
=> Add SET command for run-time configuration of keyset_id

docs/reference/index.md, packages/cipherstash-proxy/src/encrypt/mod.rs
Replace hardcoded 3KB estimate with actual ScopedCipher struct size calculation:
- Add SCOPED_CIPHER_SIZE constant using std::mem::size_of
- Update cache weigher to use accurate size (~56 bytes vs 3KB estimate)
- Update max_capacity calculation to match weigher
- Improves cache efficiency by allowing ~50x more entries with same memory footprint
=> refactor: ♻️ use std::mem::size_of for accurate cipher cache sizing

packages/cipherstash-proxy/src/postgresql/context/mod.rs, packages/cipherstash-proxy/src/postgresql/frontend.rs, packages/cipherstash-proxy/src/postgresql/messages/bind.rs, packages/cipherstash-proxy/src/postgresql/messages/close.rs, packages/cipherstash-proxy/src/postgresql/messages/describe.rs, packages/cipherstash-proxy/src/postgresql/messages/execute.rs, packages/cipherstash-proxy/src/postgresql/messages/mod.rs, packages/cipherstash-proxy/src/postgresql/messages/name.rs, packages/cipherstash-proxy/src/postgresql/messages/parse.rs, packages/cipherstash-proxy/src/postgresql/messages/target.rs
♻️ refactor: convert Name struct to enum and extract to own module
- Convert Name from struct to enum with Named(String) and Unnamed variants
- Extract Name type into dedicated name.rs module for better organization
- Add From<String> and From<&str> implementations for convenient construction
- Update all usage sites to use Name::from() constructor
- Update field access from .0 to .as_str() method
- Maintain backward compatibility through re-exports and Deref trait
- Improve type safety by preventing empty named statements
=> ♻️ refactor: convert Name struct to enum and extract to own module

DEVELOPMENT.md, packages/cipherstash-proxy/src/config/log.rs, packages/cipherstash-proxy/src/log/mod.rs, packages/cipherstash-proxy/src/log/subscriber.rs, packages/cipherstash-proxy/src/log/targets.rs
Replace manual log target management with a declarative macro system that defines all targets in one place. This eliminates the need to update 4-5 places when adding new targets and ensures consistency.
Key changes:
- Create log/targets.rs with define_log_targets! macro
- Generate target constants, functions, and level mappings automatically
- Update LogConfig to use centrally-defined field list
- Maintain all existing functionality and public API
Benefits:
- Single source of truth for log targets
- Compile-time safety between targets and config fields
- Self-documenting and easier to maintain
- Eliminates repetitive boilerplate code
=> refactor: centralize log target definitions using declarative macro

packages/cipherstash-proxy/src/postgresql/frontend.rs, packages/cipherstash-proxy/src/postgresql/mod.rs, packages/cipherstash-proxy/src/postgresql/parser.rs
Move parse_statement and parse_statements functions from Frontend to new SqlParser module to reduce cognitive load and improve code organization.
- Create packages/cipherstash-proxy/src/postgresql/parser.rs with SqlParser struct
- Move parsing functions with metrics tracking intact
- Update frontend.rs to use SqlParser::parse_statement and SqlParser::parse_statements
- Clean up unused imports and constants in frontend.rs
=> ♻️ refactor: extract SQL parsing logic into dedicated Parser module

docker-compose.yml, tests/docker-compose.yml
Previously Proxy's test harness was using images tagged `postgres:latest`, which was pointing to the latest release in the Postgres 17 series.
Postgres 18 was released in the last 24 hours, and `postgres:latest` now points to Postgres 18.
There seem to be some changes in the Postgres 18 containers, and volume mounting now [breaks](https://github.com/cipherstash/proxy/actions/runs/18117984660/job/51557338645) [consistently](https://github.com/cipherstash/proxy/actions/runs/18091500210/job/51472969879) in [CI](https://github.com/cipherstash/proxy/actions/runs/18091500241/job/51472969789?pr=328) and locally.
For now we will pin the test harness to Postgres 17, and look at supporting Postgres 18 in a subsequent PR.
By submitting this pull request, I confirm that CipherStash can use, modify, …
=> fix: pin tests to Postgres 17

docs/reference/index.md, packages/cipherstash-proxy-integration/src/migrate/mod.rs, packages/cipherstash-proxy/src/cli/mod.rs, packages/cipherstash-proxy/src/config/database.rs, packages/cipherstash-proxy/src/config/log.rs, packages/cipherstash-proxy/src/config/tandem.rs, packages/cipherstash-proxy/src/proxy/mod.rs
Adds optional command line args to proxy for specifying the database, host and username.
If not provided, env and config is used as now.
If running in docker this has no effect but is very useful if running the binary directly.
=> feat(config): add optional database connection CLI args
