cipherstash/proxy

packages/cipherstash-proxy-integration/src/map_params.rs, packages/cipherstash-proxy/Cargo.toml, packages/cipherstash-proxy/src/encrypt/mod.rs
- update cs-client for json fix
- add test for jsonb containing a number
=> Fix jsonb handling of numbers

packages/cipherstash-proxy/src/eql/mod.rs
Fix for  identifier "table" and "column"  properties to be serialized  into EQL JSON instead of the short names, "t" and "c"
=> fix(eql): EQL identifier seralized with short field names

packages/eql-mapper/src/eql_mapper.rs, packages/eql-mapper/src/model/type_system.rs
Fix some error messages left over from a debugging session > 2 months ago by Yours Truly :P
=> chore: fix accidental error messages

README.md, docker-compose.yml
A bunch of small tweaks identified during usability testing.
=> docs(getting-started): make users more successful when following the getting started 

packages/cipherstash-proxy/src/config/tandem.rs
remove println leftover from dev
=> fix(config): remove println statement

mise.local.example.toml, mise.toml
=> Bump EQL to 1.0.0 🚀

README.md, docs/getting-started/commands.sql, mise.toml, packages/cipherstash-proxy-integration/src/map_match_index.rs
Updates to latest EQL for match operator fixes
=> docs(onboard): Add match operator example to getting started

README.md
Added a footer to the README so that users can give us feedback on our docs
=> Chore: add footer to README to trigger docs issue

docs/encrypt-tool.md
=> Fix: encrypt tool Table of Content links

Cargo.lock, Cargo.toml
=> chore: bump sqltk to v0.8.0

packages/eql-mapper/src/lib.rs, packages/eql-mapper/src/transformation_rules/helpers.rs, packages/eql-mapper/src/transformation_rules/mod.rs, packages/eql-mapper/src/transformation_rules/wrap_eql_params_in_row.rs, packages/eql-mapper/src/type_checked_statement.rs
=> fix(mapper): wrap placeholders for EQL types in `ROW(..)`

.github/workflows/test.yml, Cargo.lock, packages/cipherstash-proxy-integration/Cargo.toml, packages/cipherstash-proxy/Cargo.toml
=> fix(proxy): depend on latest cipherstash-client

docs/getting-started/schema-example.sql, docs/how-to.md, mise.toml, packages/cipherstash-proxy/src/encrypt/mod.rs, packages/cipherstash-proxy/src/eql/mod.rs, packages/eql-mapper/src/lib.rs, packages/eql-mapper/src/transformation_rules/group_by_eql_col.rs, packages/eql-mapper/src/transformation_rules/wrap_eql_cols_in_order_by_with_ore_fn.rs, tests/sql/schema.sql
Align with EQL updates:
https://github.com/cipherstash/encrypt-query-language/pull/109
=> Update to use EQL 2.0.1

.github/workflows/release-aws-marketplace.yml
Added steps to dump out the contents of the OIDC claim and the GITHUB_* environment so I can see what is going on in the workflow.
=> Add env debugging to release-aws-marketplace workflow

packages/cipherstash-proxy-integration/src/lib.rs, packages/cipherstash-proxy-integration/src/update/mod.rs, packages/cipherstash-proxy-integration/src/update/update_domain_type.rs, packages/cipherstash-proxy-integration/src/update/update_with_literal.rs, packages/cipherstash-proxy-integration/src/update/update_with_null_literal.rs, packages/cipherstash-proxy-integration/src/update/update_with_null_param.rs, packages/cipherstash-proxy-integration/src/update/update_with_param.rs
UPDATE tests following the implementation patterns of the INSERT tests.
Collects all of the update tests into a single update module, covering both simple and extended protocols
=> Tests for SQL UPDATE

tests/integration/golang/Dockerfile, tests/integration/golang/README.md, tests/integration/golang/jsonb_test.go, tests/integration/golang/pgx_test.go
This ports the [tests in Rust](https://github.com/cipherstash/proxy/tree/main/packages/cipherstash-proxy-integration/src/select) to golang following the style in the [golang directory](https://github.com/cipherstash/proxy/tree/main/tests/integration/golang).
=> Integration tests in golang with pgx

mise.toml
=> chore: eql upgrade to 2.1.3

.ct.yaml, .github/workflows/release-chart.yml
Fixes an issue related to the release process of the Helm chart 
=> fix(helm): PR_BYPASS release process post merge

.github/workflows/lint-test-chart.yml
=> fix(helm): PR_BYPASS linting misconfiguration

Cargo.lock, Cargo.toml, mise.toml, packages/cipherstash-proxy-integration/Cargo.toml, packages/cipherstash-proxy-integration/src/common.rs, packages/cipherstash-proxy-integration/src/select/jsonb_array_elements.rs, packages/cipherstash-proxy-integration/src/select/jsonb_array_length.rs, packages/cipherstash-proxy-integration/src/select/mod.rs, packages/cipherstash-proxy/Cargo.toml, packages/cipherstash-proxy/src/connect/async_stream.rs, packages/cipherstash-proxy/src/encrypt/mod.rs, packages/cipherstash-proxy/src/main.rs, packages/cipherstash-proxy/src/postgresql/backend.rs, packages/cipherstash-proxy/src/postgresql/frontend.rs, packages/cipherstash-proxy/src/tls/mod.rs
Tests array handling functions and the use of the array element selector (`@`)
So far:
- jsonb_array_length
- jsonb_array_elements
=> Integration tests for jsonb array functions

Cargo.lock, packages/cipherstash-proxy-integration/Cargo.toml, packages/cipherstash-proxy/Cargo.toml, packages/eql-mapper/Cargo.toml
Using `cargo machete` to identify unused crates.
=> Remove unused dependencies

.github/workflows/benchmark.yml, .github/workflows/release.yml, .github/workflows/test.yml
Accidental merge -> Reverts cipherstash/proxy#301
=> Revert PR_BYPASS ".github/workflows: Migrate workflows to Blacksmith runners"

docs/errors.md, packages/cipherstash-proxy-integration/src/multitenant/set_keyset_id.rs, packages/cipherstash-proxy-integration/src/multitenant/set_keyset_name.rs, packages/cipherstash-proxy/src/error.rs, packages/cipherstash-proxy/src/proxy/mod.rs, packages/cipherstash-proxy/src/proxy/zerokms/mod.rs, packages/cipherstash-proxy/src/proxy/zerokms/zerokms.rs
Improve ZeroKMS error handling and startup validation to ensure users get immediate, actionable feedback when ZeroKMS authentication fails rather than encountering cryptic errors during operation.
- Add dedicated ZeroKMSError type with clearer authentication failure messages
- Validate ZeroKMS connection during proxy startup to fail fast on credential issues
- Improve error documentation with step-by-step troubleshooting guidance
- Enhanced logging with connection status and initialization feedback
- Better error categorization for credential vs system issues
Refactor: extract ZeroKMS functionality into dedicated module
- Move ZeroKMS-related encryption/decryption logic from proxy/mod.rs into a dedicated zerokms module for better code organization and maintainability.
=> fix: improve ZeroKMS error handling and startup validation
